# Generated by Django 4.2.6 on 2023-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlagData',
            fields=[
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('flag_img', models.CharField(max_length=6)),
            ],
        ),
    ]
