# Generated by Django 4.2.6 on 2023-10-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagdata',
            name='flag_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='flagdata',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='flagdata',
            name='short_name',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='short_name'),
        ),
    ]
